CREATE TABLE `sql_scenario_module` (
    `id` varchar(50) NOT NULL COMMENT '场景模块pk',
    `name` varchar(255) NOT NULL COMMENT '模块名称',
    `pos` bigint NOT NULL COMMENT '排序',
    `create_time` bigint NOT NULL COMMENT '创建时间',
    `update_time` bigint NOT NULL COMMENT '更新时间',
    `update_user` varchar(50) NOT NULL COMMENT '更新人',
    `create_user` varchar(50) NOT NULL COMMENT '创建人',
    `project_id` varchar(50) NOT NULL COMMENT '项目fk',
    `parent_id` varchar(50) NOT NULL DEFAULT 'NONE' COMMENT '父级fk',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_name_project_parent_type` (`project_id`,`name`,`parent_id`),
    KEY `idx_project_id` (`project_id`),
    KEY `idx_pos` (`pos`)
) COMMENT='场景模块';

CREATE TABLE `sql_scenario` (
    `id` varchar(50)  NOT NULL COMMENT 'id',
    `name` varchar(255)  NOT NULL COMMENT '场景名称',
    `priority` varchar(10)  NOT NULL COMMENT '场景级别/P0/P1等',
    `status` varchar(20)  NOT NULL COMMENT '场景状态/未规划/已完成 等',
    `step_total` int NOT NULL DEFAULT '0' COMMENT '场景步骤总数',
    `request_pass_rate` varchar(20)  NOT NULL DEFAULT 'Calculating' COMMENT '请求通过率',
    `last_report_status` varchar(50)  NOT NULL DEFAULT '' COMMENT '最后一次执行的结果状态',
    `last_report_id` varchar(50)  DEFAULT NULL COMMENT '最后一次执行的报告fk',
    `num` bigint NOT NULL COMMENT '编号',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '删除状态',
    `pos` bigint NOT NULL COMMENT '自定义排序',
    `version_id` varchar(50)  NOT NULL COMMENT '版本fk',
    `ref_id` varchar(50)  NOT NULL COMMENT '引用资源fk',
    `latest` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否为最新版本 0:否，1:是',
    `project_id` varchar(50)  NOT NULL COMMENT '项目fk',
    `module_id` varchar(50)  NOT NULL COMMENT '场景模块fk',
    `description` varchar(1000)  DEFAULT NULL COMMENT '描述信息',
    `tags` varchar(1000)  DEFAULT NULL COMMENT '标签',
    `grouped` bit(1) DEFAULT b'0' COMMENT '是否为环境组',
    `environment_id` varchar(50)  DEFAULT NULL COMMENT '环境或者环境组ID',
    `create_user` varchar(50)  NOT NULL COMMENT '创建人',
    `create_time` bigint NOT NULL COMMENT '创建时间',
    `delete_time` bigint DEFAULT NULL COMMENT '删除时间',
    `delete_user` varchar(50)  DEFAULT NULL COMMENT '删除人',
    `update_user` varchar(50)  NOT NULL COMMENT '更新人',
    `update_time` bigint NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_module_id` (`module_id`),
    KEY `idx_ref_id` (`ref_id`),
    KEY `idx_version_id` (`version_id`),
    KEY `idx_project_id` (`project_id`),
    KEY `idx_status` (`status`),
    KEY `idx_report_status` (`last_report_status`),
    KEY `idx_create_time` (`create_time` DESC),
    KEY `idx_update_time` (`update_time` DESC),
    KEY `idx_num` (`num`),
    KEY `idx_priority` (`priority`),
    KEY `idx_name` (`name`),
    KEY `idx_project_id_delete_create_time` (`project_id`,`deleted`,`create_time`),
    KEY `idx_project_id_delete_create_time_create_user` (`project_id`,`deleted`,`create_time`,`create_user`)
) COMMENT='场景';

CREATE TABLE `sql_scenario_blob` (
    `id` varchar(50)  NOT NULL COMMENT '场景pk',
    `config` longblob COMMENT '场景配置信息',
    PRIMARY KEY (`id`)
) COMMENT='场景配置信息等详情';