CREATE TABLE `sql_exec_task` (
    `id` varchar(50) NOT NULL COMMENT '任务ID',
    `num` bigint NOT NULL COMMENT '编号',
    `task_name` varchar(255) NOT NULL COMMENT '任务名称',
    `status` varchar(20) NOT NULL COMMENT '状态',
    `case_count` bigint NOT NULL COMMENT '用例数量',
    `result` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '执行结果',
    `task_type` varchar(50) NOT NULL COMMENT '任务类型',
    `resource_id` varchar(50) DEFAULT NULL COMMENT '测试计划id/测试计划组id',
    `trigger_mode` varchar(20) NOT NULL COMMENT '执行模式',
    `project_id` varchar(50) NOT NULL COMMENT '项目ID',
    `organization_id` varchar(50) NOT NULL COMMENT '组织ID',
    `integrated` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否是集成报告',
    `create_time` bigint NOT NULL COMMENT '创建时间',
    `create_user` varchar(50) NOT NULL COMMENT '创建人',
    `start_time` bigint DEFAULT NULL COMMENT '开始时间',
    `end_time` bigint DEFAULT NULL COMMENT '结束时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '删除标识',
    `parallel` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否是并行执行',
    `environment_id` varchar(50) DEFAULT NULL COMMENT '用例批量执行环境ID',
    `env_grouped` bit(1) DEFAULT b'0' COMMENT '是否是环境组',
    `pool_id` varchar(50) DEFAULT NULL COMMENT '资源池ID',
    PRIMARY KEY (`id`),
    KEY `idx_num` (`num`),
    KEY `idx_name` (`task_name`),
    KEY `idx_status` (`status`),
    KEY `idx_result` (`result`),
    KEY `idx_project_id` (`project_id`),
    KEY `idx_organization_id` (`organization_id`),
    KEY `idx_start_time` (`start_time`),
    KEY `idx_end_time` (`end_time`),
    KEY `idx_trigger_mode` (`trigger_mode`)
) COMMENT='SQL执行任务表';

CREATE TABLE `sql_exec_task_item` (
    `id` varchar(50) NOT NULL COMMENT '主键ID',
    `task_id` varchar(50) NOT NULL COMMENT '任务ID',
    `resource_id` varchar(50) NOT NULL COMMENT '资源ID',
    `resource_name` varchar(255) NOT NULL COMMENT '资源名称',
    `task_origin` varchar(50) DEFAULT NULL COMMENT '任务来源（任务组下的任务id）',
    `status` varchar(20) NOT NULL COMMENT '执行状态',
    `result` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '执行结果',
    `resource_pool_id` varchar(50) NOT NULL COMMENT '资源池ID',
    `resource_pool_node` varchar(50) DEFAULT NULL COMMENT '节点',
    `resource_type` varchar(50) NOT NULL COMMENT '资源类型',
    `project_id` varchar(50) NOT NULL COMMENT '项目ID',
    `organization_id` varchar(50) NOT NULL COMMENT '组织ID',
    `thread_id` varchar(50) DEFAULT NULL COMMENT '线程ID',
    `start_time` bigint DEFAULT NULL COMMENT '执行开始时间',
    `end_time` bigint DEFAULT NULL COMMENT '执行完成时间',
    `executor` varchar(50) NOT NULL COMMENT '执行人',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '删除标识',
    `case_id` varchar(50) DEFAULT NULL COMMENT '用例表id',
    `collection_id` varchar(50) DEFAULT NULL COMMENT '测试集ID',
    `error_message` varchar(50) DEFAULT NULL COMMENT '异常信息',
    `rerun` bit(1) DEFAULT b'0' COMMENT '是否是重跑任务项',
    `create_time` bigint NOT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_task_id` (`task_id`),
    KEY `idx_resource_id` (`resource_id`),
    KEY `idx_resource_name` (`resource_name`),
    KEY `idx_status` (`status`),
    KEY `idx_result` (`result`),
    KEY `idx_project_id` (`project_id`),
    KEY `idx_organization_id` (`organization_id`),
    KEY `idx_start_time` (`start_time` DESC),
    KEY `idx_end_time` (`end_time` DESC),
    KEY `idx_executor` (`executor`),
    KEY `idx_case_id` (`case_id`)
) COMMENT='执行任务详情表'