CREATE TABLE `sql_scenario_report` (
    `id` varchar(50) NOT NULL COMMENT '场景报告pk',
    `name` varchar(300) NOT NULL COMMENT '报告名称',
    `test_plan_scenario_id` varchar(50) NOT NULL DEFAULT 'NONE' COMMENT '测试计划关联场景表ID',
    `create_user` varchar(50) NOT NULL COMMENT '创建人',
    `delete_time` bigint DEFAULT NULL COMMENT '删除时间',
    `delete_user` varchar(50) DEFAULT NULL COMMENT '删除人',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '删除标识',
    `update_user` varchar(50) NOT NULL COMMENT '修改人',
    `update_time` bigint NOT NULL COMMENT '更新时间',
    `start_time` bigint NOT NULL COMMENT '开始时间/同创建时间一致',
    `end_time` bigint DEFAULT NULL COMMENT '结束时间/报告执行完成',
    `request_duration` bigint NOT NULL DEFAULT '0' COMMENT '请求总耗时',
    `status` varchar(20) NOT NULL DEFAULT '-' COMMENT '报告状态/SUCCESS/ERROR',
    `trigger_mode` varchar(20) NOT NULL COMMENT '触发方式',
    `run_mode` varchar(20) NOT NULL COMMENT '执行模式',
    `pool_id` varchar(50) NOT NULL DEFAULT '0' COMMENT '资源池',
    `integrated` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否是集成报告',
    `project_id` varchar(50) NOT NULL COMMENT '项目fk',
    `environment_id` varchar(50) DEFAULT NULL COMMENT '环境',
    `error_count` bigint NOT NULL DEFAULT '0' COMMENT '失败数',
    `fake_error_count` bigint NOT NULL DEFAULT '0' COMMENT '误报数',
    `pending_count` bigint NOT NULL DEFAULT '0' COMMENT '未执行数',
    `success_count` bigint NOT NULL DEFAULT '0' COMMENT '成功数',
    `assertion_count` bigint NOT NULL DEFAULT '0' COMMENT '总断言数',
    `assertion_success_count` bigint NOT NULL DEFAULT '0' COMMENT '成功断言数',
    `request_error_rate` varchar(20) NOT NULL DEFAULT 'Calculating' COMMENT '请求失败率',
    `request_pending_rate` varchar(20) NOT NULL DEFAULT 'Calculating' COMMENT '请求未执行率',
    `request_fake_error_rate` varchar(20) NOT NULL DEFAULT 'Calculating' COMMENT '请求误报率',
    `request_pass_rate` varchar(20) NOT NULL DEFAULT 'Calculating' COMMENT '请求通过率',
    `assertion_pass_rate` varchar(20) NOT NULL DEFAULT 'Calculating' COMMENT '断言通过率',
    `script_identifier` varchar(255) DEFAULT NULL COMMENT '脚本标识',
    `waiting_time` bigint DEFAULT NULL COMMENT '等待时间',
    `exec_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '执行状态',
    `plan` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否是测试计划整体执行',
    PRIMARY KEY (`id`),
    KEY `idx_project_id` (`project_id`),
    KEY `idx_trigger_mode` (`trigger_mode`),
    KEY `idx_run_mode` (`run_mode`),
    KEY `idx_status` (`status`),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_create_user` (`create_user`),
    KEY `idx_name` (`name`),
    KEY `idx_pool_id` (`pool_id`),
    KEY `idx_integrated` (`integrated`),
    KEY `idx_start_time` (`start_time`),
    KEY `idx_exec_status` (`exec_status`),
    KEY `idx_test_plan_scenario_id` (`test_plan_scenario_id`),
    KEY `idx_plan` (`plan`)
) COMMENT='SQL场景报告'